// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Versione dell'app, dal `Cargo.toml`. */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	/**
	 *  Apre il dialog di sistema sui file accettati. `filter_name` è l'etichetta tradotta del filtro.
	 *  Restituisce il percorso scelto, o `null` se l'utente annulla.
	 */
	pickSource: (filterName: string) => __TAURI_INVOKE<string | null>("pick_source", { filterName }),
	/**
	 *  Apre la Sorgente con il programma associato. Accetta solo le estensioni di Sfoglia, così
	 *  non diventa un modo per lanciare eseguibili.
	 */
	openSource: (source: string) => typedError<null, AppError>(__TAURI_INVOKE("open_source", { source })),
	/**
	 *  Trascrive la Sorgente: progresso e Frasi arrivano come eventi, poi il testo si salva nel TXT.
	 *  Rifiuta con `activityInProgress` se un'Attività è già in corso, e finisce con `cancelled` dopo
	 *  `cancel_transcription`.
	 */
	transcribe: (source: string) => typedError<TranscriptionOutcome, AppError>(__TAURI_INVOKE("transcribe", { source })),
	/**  Annulla la Trascrizione in corso. Restituisce `false` se non è (ancora) partita. */
	cancelTranscription: () => __TAURI_INVOKE<boolean>("cancel_transcription"),
	/**  I modelli del catalogo con il loro stato. */
	listModels: () => __TAURI_INVOKE<ModelInfo[]>("list_models"),
	/**
	 *  Avvia il download di un modello in background, o lo riprende da un parziale. Avanzamento ed
	 *  esito arrivano con `model-download-progress` e `model-state-changed`.
	 */
	downloadModel: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("download_model", { id })),
	/**  Annulla il download e cancella il parziale. Restituisce `false` se non c'era un download. */
	cancelModelDownload: (id: string) => __TAURI_INVOKE<boolean>("cancel_model_download", { id }),
	/**
	 *  Elimina il modello scaricato. Rifiuta con `modelInUse` se si sta caricando o lo usa una
	 *  Trascrizione.
	 */
	deleteModel: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_model", { id })),
	/**  Le impostazioni correnti, lette all'avvio. */
	getSettings: () => __TAURI_INVOKE<Settings>("get_settings"),
	/**  Valida e salva le impostazioni. Se cambia il modello scelto, lo carica in background. */
	setSettings: (settings: Settings) => typedError<null, AppError>(__TAURI_INVOKE("set_settings", { settings })),
	/**  I microfoni rilevati, per la scelta in Impostazioni. */
	listMicrophones: () => typedError<AudioDevice[], AppError>(__TAURI_INVOKE("list_microphones")),
	/**  I dispositivi di uscita rilevati, per la scelta dell'audio di sistema in Impostazioni. */
	listOutputDevices: () => typedError<AudioDevice[], AppError>(__TAURI_INVOKE("list_output_devices")),
	/**
	 *  Registra dagli ingressi delle impostazioni (microfono, audio di sistema o entrambi) finché
	 *  arriva `stop_recording` o un dispositivo si scollega; poi il file diventa la Sorgente. Durata e
	 *  livelli arrivano con `recording-tick`. `prefix` è il prefisso tradotto del nome del file. Rifiuta
	 *  con `activityInProgress` se un'Attività è già in corso.
	 */
	record: (prefix: string) => typedError<RecordingSaved, AppError>(__TAURI_INVOKE("record", { prefix })),
	/**  Mette in pausa (`true`) o riprende la Registrazione. Restituisce `false` se non è in corso. */
	pauseRecording: (paused: boolean) => __TAURI_INVOKE<boolean>("pause_recording", { paused }),
	/**
	 *  Ferma e salva la Registrazione: l'esito arriva come risultato di `record`. Restituisce
	 *  `false` se non è in corso.
	 */
	stopRecording: () => __TAURI_INVOKE<boolean>("stop_recording"),
	/**  La Cartella predefinita in uso: quella delle impostazioni o `Documenti\Sbobino`. */
	recordingsFolder: () => typedError<string, AppError>(__TAURI_INVOKE("recordings_folder")),
	/**  Apre il dialog di sistema per scegliere una cartella. `null` se l'utente annulla. */
	pickFolder: () => __TAURI_INVOKE<string | null>("pick_folder"),
};

/** Events */
export const events = {
	modelDownloadProgress: makeEvent<ModelDownloadProgress>("model-download-progress"),
	modelStateChanged: makeEvent<ModelStateChanged>("model-state-changed"),
	recordingTick: makeEvent<RecordingTick>("recording-tick"),
	transcriptPartial: makeEvent<TranscriptPartial>("transcript-partial"),
	transcriptPhrase: makeEvent<TranscriptPhrase>("transcript-phrase"),
	transcriptionProgress: makeEvent<TranscriptionProgress>("transcription-progress"),
};

/* Types */
export type AppError = { code: "unreadableFile"; detail: string } | { code: "unsupportedCodec"; detail: string } | { code: "unwritableFolder"; detail: string } | { code: "modelMissing"; detail: string } | 
/**  Il modello si sta caricando o lo usa una Trascrizione: non si elimina. */
{ code: "modelInUse"; detail: string } | { code: "downloadFailed"; detail: string } | 
/**  Dimensione o SHA-256 del modello scaricato non corrispondono al catalogo. */
{ code: "verificationFailed"; detail: string } | 
/**  Il dispositivo si è scollegato durante la Registrazione, che si è salvata: porta il nome. */
{ code: "deviceDisconnected"; detail: string } | 
/**  Nessun microfono, o quello scelto in Impostazioni non è collegato. */
{ code: "microphoneMissing" } | 
/**  Nessun dispositivo di uscita per l'audio di sistema, o quello scelto non è collegato. */
{ code: "outputDeviceMissing" } | { code: "activityInProgress" } | { code: "cancelled" } | { code: "internal"; detail: string };

/**  Un microfono o un dispositivo di uscita, per la scelta in Impostazioni. */
export type AudioDevice = {
	/**  L'id stabile di cpal (`wasapi:{…}`), salvato nelle impostazioni. */
	id: string,
	name: string,
	isDefault: boolean,
};

export type Channels = "mono" | "stereo";

/**  Le sei lingue dell'interfaccia. */
export type Language = "it" | "en" | "fr" | "es" | "de" | "pl";

/**  Il picco, tra 0 e 1, di ogni ingresso; `null` per quello che non si registra. */
export type Levels = {
	microphone: number | null,
	system: number | null,
};

/**  Come compare il testo: con i Parziali mentre la Frase è in corso, o a fine Frase. */
export type Mode = "stream" | "frase";

/**  Avanzamento del download di un modello, al massimo 10 volte al secondo. */
export type ModelDownloadProgress = {
	modelId: string,
	percent: number,
};

/**  Un modello del catalogo con il suo stato, per Impostazioni → Trascrizione. */
export type ModelInfo = {
	id: string,
	name: string,
	/**  Byte da scaricare. */
	size: number,
	mode: Mode,
	license: string,
	/**  Consigliato e predefinito. */
	recommended: boolean,
	state: ModelState,
	/**  L'errore dell'ultimo download, finché non se ne avvia un altro. */
	error: AppError | null,
	/**
	 *  Le lingue che il modello accetta come indicazione (`it`, `it-IT`…), lette dal modello
	 *  caricato. `null` finché non è stato caricato almeno una volta.
	 */
	languages: string[] | null,
	/**  Il modello si sta caricando o lo usa una Trascrizione: non si elimina. */
	inUse: boolean,
};

/**  Lo stato di un modello per l'interfaccia. */
export type ModelState = { state: "notDownloaded" } | 
/**  Un download interrotto: il `.partial` resta e il prossimo download riprende da lì. */
{ state: "interrupted"; percent: number } | { state: "downloading"; percent: number } | 
/**  Controllo di dimensione e SHA-256 prima che il modello diventi utilizzabile. */
{ state: "verifying" } | { state: "downloaded" };

/**  Un modello ha cambiato stato: download avviato, in verifica, finito, fallito, eliminato. */
export type ModelStateChanged = {
	modelId: string,
	state: ModelState,
	error: AppError | null,
};

/**  La Registrazione salvata, che diventa la Sorgente. */
export type RecordingSaved = {
	path: string,
	/**
	 *  Perché la Registrazione si è fermata da sola (`deviceDisconnected`, `unwritableFolder`);
	 *  `null` dopo Stop.
	 */
	error: AppError | null,
};

export type RecordingSource = "mic" | "system" | "both";

/**  Durata registrata (pause escluse) e livelli dall'evento precedente. */
export type RecordingTick = {
	elapsedMs: number,
	levels: Levels,
};

export type Settings = {
	recordingSource: RecordingSource,
	/**  `null`: il microfono predefinito di sistema. */
	microphone: string | null,
	/**  `null`: il dispositivo di uscita predefinito, per l'audio di sistema. */
	outputDevice: string | null,
	/**  L'id del modello nel catalogo. */
	model: string,
	speechLanguage: SpeechLanguage,
	bitrateKbps: number,
	channels: Channels,
	/**  Hz. */
	sampleRate: number,
	/**  `null`: `Documenti\Sbobino`. */
	recordingsFolder: string | null,
	/**  `null`: la lingua di sistema se è tra le sei, altrimenti l'inglese. */
	interfaceLanguage: Language | null,
};

/**  La Lingua del parlato: Automatica o una delle sei lingue dell'app. */
export type SpeechLanguage = "auto" | "it" | "en" | "fr" | "es" | "de" | "pl";

/**
 *  Il Parziale della Frase in corso (solo con i modelli in streaming): sostituisce il precedente e
 *  ha l'id che avrà la Frase.
 */
export type TranscriptPartial = {
	phraseId: number,
	text: string,
};

/**  Una Frase conclusa, una per riga nell'area di testo. Sostituisce il Parziale con lo stesso id. */
export type TranscriptPhrase = {
	phraseId: number,
	text: string,
};

/**  Dove è il TXT salvato e quanti caratteri contiene. */
export type TranscriptionFinished = {
	txtPath: string,
	chars: number,
};

/**  Esito di una Trascrizione arrivata alla fine della Sorgente. Annulla e i guasti sono `AppError`. */
export type TranscriptionOutcome = 
/**  Il testo è salvato nel TXT. */
{
	outcome: "saved",
} & TranscriptionFinished | 
/**  Nessuna Frase: il TXT non si crea. */
{ outcome: "noSpeech" };

/**  Avanzamento della Trascrizione: `percent` è `null` se la durata della Sorgente non è nota. */
export type TranscriptionProgress = {
	percent: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

