// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Versione dell'app, dal `Cargo.toml`. */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
};

