// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  Versione dell'app, dal `Cargo.toml`. */
	appVersion: () => __TAURI_INVOKE<string>("app_version"),
	/**
	 *  Apre il dialog di sistema sui file accettati. `filter_name` è l'etichetta tradotta del filtro.
	 *  Restituisce il percorso scelto, o `null` se l'utente annulla.
	 */
	pickSource: (filterName: string) => __TAURI_INVOKE<string | null>("pick_source", { filterName }),
	/**
	 *  Apre la Sorgente con il programma associato; un Bino lo mostra nella cartella. Accetta solo le
	 *  estensioni di Apri file, così non diventa un modo per lanciare eseguibili.
	 */
	openSource: (source: string) => typedError<null, AppError>(__TAURI_INVOKE("open_source", { source })),
	/**
	 *  Trascrive la Sorgente: progresso e Frasi arrivano come eventi. Un file audio o video diventa un
	 *  Bino nella Raccolta `raccolta` (`null` o `""`: la radice della Libreria), di un Bino si
	 *  riscrive il testo.
	 *  Rifiuta con `activityInProgress` se un'Attività è già in corso, e finisce con `cancelled` dopo
	 *  `cancel_transcription`.
	 */
	transcribe: (source: string, raccolta: string | null) => typedError<TranscriptionOutcome, AppError>(__TAURI_INVOKE("transcribe", { source, raccolta })),
	/**  Annulla la Trascrizione in corso. Restituisce `false` se non è (ancora) partita. */
	cancelTranscription: () => __TAURI_INVOKE<boolean>("cancel_transcription"),
	/**
	 *  Il testo di Copia testo della Trascrizione in corso o appena finita senza Bino: in testo semplice
	 *  o Markdown, secondo `copiaCome`. `null` se non c'è ancora stata una Trascrizione.
	 */
	transcriptText: () => __TAURI_INVOKE<string | null>("transcript_text"),
	/**
	 *  Apre un Bino scelto come Sorgente: restituisce le sue Frasi, i nomi dei Parlanti e le
	 *  informazioni. `unsupportedBino` se viene da una versione più nuova dell'app.
	 */
	openBino: (source: string) => typedError<OpenedBino, AppError>(__TAURI_INVOKE("open_bino", { source })),
	/**
	 *  Dà il nome `nome` al Parlante `parlante` di `ingresso` nel Bino `path`. Rifiuta un nome vuoto, e
	 *  con `activityInProgress` il Bino su cui lavora l'Attività in corso.
	 */
	renameParlante: (path: string, ingresso: Ingresso, parlante: number, nome: string) => typedError<null, AppError>(__TAURI_INVOKE("rename_parlante", { path, ingresso, parlante, nome })),
	/**
	 *  Corregge il testo della Frase `phrase_id` di `ingresso` nel Bino `path`; tempi, Parlanti e audio
	 *  restano com'erano. Rifiuta con `activityInProgress` il Bino su cui lavora l'Attività in corso.
	 */
	editFrase: (path: string, ingresso: Ingresso, phraseId: number, testo: string) => typedError<null, AppError>(__TAURI_INVOKE("edit_frase", { path, ingresso, phraseId, testo })),
	/**  Il testo di Copia testo del Bino `path`, con correzioni e nomi dei Parlanti, secondo `copiaCome`. */
	binoText: (path: string) => typedError<string, AppError>(__TAURI_INVOKE("bino_text", { path })),
	/**
	 *  Salva il Markdown del Bino `path` dove sceglie l'utente nel dialog di sistema, proponendo
	 *  `<titolo>.md`. Restituisce il file scritto, o `null` se l'utente annulla.
	 */
	exportMarkdown: (path: string) => typedError<string | null, AppError>(__TAURI_INVOKE("export_markdown", { path })),
	/**
	 *  Il Bino arrivato con un avvio (doppio clic in Esplora file) e non ancora aperto, se c'è; dopo
	 *  la chiamata non c'è più. `bino-requested` avvisa quando ne arriva uno con l'app già aperta.
	 */
	takePendingBino: () => __TAURI_INVOKE<string | null>("take_pending_bino"),
	/**  I modelli del catalogo con il loro stato. */
	listModels: () => __TAURI_INVOKE<ModelInfo[]>("list_models"),
	/**
	 *  Avvia il download di un modello in background, o lo riprende da un parziale. Avanzamento ed
	 *  esito arrivano con `model-download-progress` e `model-state-changed`.
	 */
	downloadModel: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("download_model", { id })),
	/**  Annulla il download e cancella il parziale. Restituisce `false` se non c'era un download. */
	cancelModelDownload: (id: string) => __TAURI_INVOKE<boolean>("cancel_model_download", { id }),
	/**
	 *  Elimina il modello scaricato. Rifiuta con `modelInUse` se si sta caricando o lo usa una
	 *  Trascrizione.
	 */
	deleteModel: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_model", { id })),
	/**
	 *  Le impostazioni lette all'avvio. `unreadableSettings` se il file non si è letto: allora il
	 *  backend usa i predefiniti.
	 */
	getSettings: () => typedError<Settings, AppError>(__TAURI_INVOKE("get_settings")),
	/**
	 *  Valida e salva le impostazioni e restituisce quelle salvate: se all'avvio il file non si è letto,
	 *  sono le sue con sopra le modifiche. Se cambia il modello scelto, lo carica in background.
	 */
	setSettings: (settings: Settings) => typedError<Settings, AppError>(__TAURI_INVOKE("set_settings", { settings })),
	/**
	 *  La lingua di Windows se è tra le sei, altrimenti l'inglese: la Lingua dell'interfaccia quando
	 *  le impostazioni non ne scelgono una.
	 */
	systemLanguage: () => __TAURI_INVOKE<Language>("system_language"),
	/**  I microfoni rilevati, per la scelta in Impostazioni. */
	listMicrophones: () => typedError<AudioDevice[], AppError>(__TAURI_INVOKE("list_microphones")),
	/**  I dispositivi di uscita rilevati, per la scelta dell'audio di sistema in Impostazioni. */
	listOutputDevices: () => typedError<AudioDevice[], AppError>(__TAURI_INVOKE("list_output_devices")),
	/**
	 *  Registra dagli ingressi delle impostazioni (microfono, audio di sistema o entrambi) finché
	 *  arriva `stop_recording` o un dispositivo si scollega; poi il Bino, nella Raccolta `raccolta`
	 *  (`null` o `""`: la radice della Libreria), diventa la Sorgente. Durata e livelli arrivano con
	 *  `recording-tick`. `prefix` è il prefisso tradotto del nome del file. Rifiuta con
	 *  `activityInProgress` se un'Attività è già in corso.
	 */
	record: (prefix: string, raccolta: string | null) => typedError<RecordingSaved, AppError>(__TAURI_INVOKE("record", { prefix, raccolta })),
	/**  Mette in pausa (`true`) o riprende la Registrazione. Restituisce `false` se non è in corso. */
	pauseRecording: (paused: boolean) => __TAURI_INVOKE<boolean>("pause_recording", { paused }),
	/**
	 *  Ferma e salva la Registrazione: l'esito arriva come risultato di `record`. Restituisce
	 *  `false` se non è in corso.
	 */
	stopRecording: () => __TAURI_INVOKE<boolean>("stop_recording"),
	/**  La Cartella della Libreria in uso: quella delle impostazioni o `Documenti\Sbobino`. */
	recordingsFolder: () => typedError<string, AppError>(__TAURI_INVOKE("recordings_folder")),
	/**  Apre il dialog di sistema per scegliere una cartella. `null` se l'utente annulla. */
	pickFolder: () => __TAURI_INVOKE<string | null>("pick_folder"),
	/**  Le Raccolte e i Bini della Libreria, dall'indice: `library-changed` avvisa quando cambiano. */
	libraryList: () => typedError<LibraryList, AppError>(__TAURI_INVOKE("library_list")),
	/**
	 *  Cerca `query` nei Bini della Raccolta `raccolta` (`null` tutta la Libreria, `""` Senza
	 *  raccolta): titoli, testo delle Frasi e nomi dei Parlanti.
	 */
	librarySearch: (query: string, raccolta: string | null) => typedError<SearchResult[], AppError>(__TAURI_INVOKE("library_search", { query, raccolta })),
	/**
	 *  Crea la Raccolta `nome`. `invalidName` per un nome che Windows non ammette, `nameTaken` se c'è
	 *  già.
	 */
	createRaccolta: (nome: string) => typedError<null, AppError>(__TAURI_INVOKE("create_raccolta", { nome })),
	/**
	 *  Rinomina la Raccolta `nome` e la sua cartella in `nuovo`, e restituisce la cartella nuova. Rifiuta
	 *  con `activityInProgress` se l'Attività in corso lavora su un suo Bino.
	 */
	renameRaccolta: (nome: string, nuovo: string) => typedError<string, AppError>(__TAURI_INVOKE("rename_raccolta", { nome, nuovo })),
	/**  Elimina la Raccolta `nome`, solo se vuota (`raccoltaNotEmpty`). */
	deleteRaccolta: (nome: string) => typedError<null, AppError>(__TAURI_INVOKE("delete_raccolta", { nome })),
	/**
	 *  Rinomina il file del Bino in `<titolo>.bino` e restituisce il percorso nuovo. Rifiuta con
	 *  `activityInProgress` il Bino su cui lavora l'Attività in corso.
	 */
	renameBino: (path: string, titolo: string) => typedError<string, AppError>(__TAURI_INVOKE("rename_bino", { path, titolo })),
	/**
	 *  Sposta il Bino nella Raccolta `raccolta` (`null` o `""`: la radice), anche da fuori della
	 *  Libreria (Aggiungi alla Libreria…), e restituisce il percorso nuovo.
	 */
	moveBino: (path: string, raccolta: string | null) => typedError<string, AppError>(__TAURI_INVOKE("move_bino", { path, raccolta })),
	/**  Manda il Bino nel Cestino di Windows. */
	trashBino: (path: string) => typedError<null, AppError>(__TAURI_INVOKE("trash_bino", { path })),
};

/** Events */
export const events = {
	binoRequested: makeEvent<BinoRequested>("bino-requested"),
	diarizationStarted: makeEvent<DiarizationStarted>("diarization-started"),
	libraryChanged: makeEvent<LibraryChanged>("library-changed"),
	liveTranscriptionFailed: makeEvent<LiveTranscriptionFailed>("live-transcription-failed"),
	modelDownloadProgress: makeEvent<ModelDownloadProgress>("model-download-progress"),
	modelStateChanged: makeEvent<ModelStateChanged>("model-state-changed"),
	recordingTick: makeEvent<RecordingTick>("recording-tick"),
	speakersAssigned: makeEvent<SpeakersAssigned>("speakers-assigned"),
	transcriptPartial: makeEvent<TranscriptPartial>("transcript-partial"),
	transcriptPhrase: makeEvent<TranscriptPhrase>("transcript-phrase"),
	transcriptionProgress: makeEvent<TranscriptionProgress>("transcription-progress"),
};

/* Types */
export type AppError = { code: "unreadableFile"; detail: string } | { code: "unsupportedCodec"; detail: string } | { code: "unwritableFolder"; detail: string } | { code: "modelMissing"; detail: string } | 
/**
 *  Riconosci i parlanti è attiva ma il modello di diarizzazione, di cui porta il nome, non è
 *  scaricato.
 */
{ code: "diarizerMissing"; detail: string } | 
/**  Il modello si sta caricando o lo usa una Trascrizione: non si elimina. */
{ code: "modelInUse"; detail: string } | { code: "downloadFailed"; detail: string } | 
/**  Dimensione o SHA-256 del modello scaricato non corrispondono al catalogo. */
{ code: "verificationFailed"; detail: string } | 
/**  Il dispositivo si è scollegato durante la Registrazione, che si è salvata: porta il nome. */
{ code: "deviceDisconnected"; detail: string } | 
/**  Nessun microfono, o quello scelto in Impostazioni non è collegato. */
{ code: "microphoneMissing" } | 
/**  Nessun dispositivo di uscita per l'audio di sistema, o quello scelto non è collegato. */
{ code: "outputDeviceMissing" } | 
/**  `settings.json` esiste ma non si legge: valgono i predefiniti. */
{ code: "unreadableSettings"; detail: string } | 
/**
 *  Il modello scelto, di cui porta il nome, non è scaricato o non si carica: la Registrazione
 *  continua senza Trascrizione dal vivo.
 */
{ code: "liveTranscriptionUnavailable"; detail: string } | 
/**  Il Bino è stato scritto da una versione più nuova dell'app, con uno schema che non conosce. */
{ code: "unsupportedBino" } | 
/**  Il nome di una Raccolta o il titolo di un Bino non è ammesso da Windows. */
{ code: "invalidName"; detail: string } | 
/**  C'è già una Raccolta, o un Bino nella stessa cartella, con questo nome. */
{ code: "nameTaken"; detail: string } | 
/**  Si elimina solo una Raccolta vuota. */
{ code: "raccoltaNotEmpty"; detail: string } | 
/**  Il Bino non è più dov'era: spostato, rinominato o cancellato fuori dall'app. */
{ code: "binoNotFound"; detail: string } | { code: "activityInProgress" } | { code: "cancelled" } | { code: "internal"; detail: string };

/**  Un microfono o un dispositivo di uscita, per la scelta in Impostazioni. */
export type AudioDevice = {
	/**  L'id stabile di cpal (`wasapi:{…}`), salvato nelle impostazioni. */
	id: string,
	name: string,
	isDefault: boolean,
};

/**  Un Bino della Libreria, come lo mostra la barra laterale. */
export type BinoEntry = {
	path: string,
	/**  `null`: Senza raccolta. */
	raccolta: string | null,
	/**  Il nome del file senza estensione. */
	titolo: string,
	/**  `creato` del Bino; per un Bino illeggibile la data di modifica del file. */
	creato: string,
	/**  `null` per un Bino illeggibile o di una versione futura. */
	durataMs: number | null,
};

/**  La riga di informazioni della vista di un Bino. */
export type BinoInfo = {
	/**  Data e ora della Registrazione o della Trascrizione, ISO 8601 con il fuso. */
	creato: string,
	durataMs: number,
	/**  Il nome del modello; `null` se il testo non è stato trascritto. */
	modello: string | null,
	linguaParlato: SpeechLanguage,
	ingressiSeparati: boolean,
	completa: boolean,
	/**  Il nome del file audio o video da cui viene. */
	origine: string | null,
};

/**  È arrivato un Bino da aprire: la finestra lo prende con `take_pending_bino`. */
export type BinoRequested = null;

export type Channels = "mono" | "stereo";

export type CopiaCome = 
/**  Testo semplice, senza sintassi Markdown. */
"testo" | "markdown";

/**  Finita la Trascrizione, comincia la Diarizzazione (Riconosci i parlanti). */
export type DiarizationStarted = null;

/**
 *  Da dove viene una Frase: dal mix, o con gli Ingressi separati dal microfono o dall'audio di
 *  sistema.
 */
export type Ingresso = "mix" | "microfono" | "sistema";

/**  Le sei lingue dell'interfaccia. */
export type Language = "it" | "en" | "fr" | "es" | "de" | "pl";

/**  Il picco, tra 0 e 1, di ogni ingresso; `null` per quello che non si registra. */
export type Levels = {
	microphone: number | null,
	system: number | null,
};

/**  L'elenco della Libreria è cambiato (o può essere cambiato): il frontend lo rilegge. */
export type LibraryChanged = null;

/**  Le Raccolte e tutti i Bini della Libreria. */
export type LibraryList = {
	/**  I nomi delle Raccolte, in ordine alfabetico. */
	raccolte: string[],
	/**  Dal più recente. */
	bini: BinoEntry[],
};

/**  Com'è finita la Trascrizione dal vivo di una Registrazione salvata. */
export type LiveTranscription = 
/**  Il testo è nel Bino o, se il Bino non si è scritto, nel Markdown accanto all'Ogg. */
{ outcome: "saved" } | { outcome: "noSpeech" } | 
/**
 *  Modello assente (`liveTranscriptionUnavailable`), guasto o Annulla (`cancelled`): il Bino ha
 *  le Frasi arrivate, con il testo incompleto.
 */
{ outcome: "failed"; error: AppError };

/**
 *  La Trascrizione dal vivo si è fermata (modello assente, guasto): la Registrazione continua senza
 *  testo.
 */
export type LiveTranscriptionFailed = {
	error: AppError,
};

/**  La modalità della Trascrizione dal vivo. */
export type ModalitaDalVivo = 
/**  Si trascrive il mix. */
"mix" | 
/**
 *  Ogni Ingresso si trascrive per conto suo, con una sua istanza del modello. Vale solo
 *  registrando da Entrambi.
 */
"ingressiSeparati";

/**  Come compare il testo: con i Parziali mentre la Frase è in corso, o a fine Frase. */
export type Mode = "stream" | "frase";

/**  Avanzamento del download di un modello, al massimo 10 volte al secondo. */
export type ModelDownloadProgress = {
	modelId: string,
	percent: number,
};

/**  Un modello del catalogo con il suo stato, per Impostazioni → Trascrizione. */
export type ModelInfo = {
	id: string,
	name: string,
	/**  Byte da scaricare. */
	size: number,
	kind: ModelKind,
	/**  `null` per il modello di diarizzazione. */
	mode: Mode | null,
	license: string,
	/**  Consigliato e predefinito. */
	recommended: boolean,
	state: ModelState,
	/**  L'errore dell'ultimo download, finché non se ne avvia un altro. */
	error: AppError | null,
	/**
	 *  Le lingue che il modello accetta come indicazione (`it`, `it-IT`…), lette dal modello
	 *  caricato. `null` finché non è stato caricato almeno una volta.
	 */
	languages: string[] | null,
	/**  Il modello si sta caricando o lo usa una Trascrizione: non si elimina. */
	inUse: boolean,
};

/**
 *  Cosa fa un modello: trascrive (si sceglie in Impostazioni), oppure diarizza (uno solo, per
 *  "Riconosci i parlanti").
 */
export type ModelKind = "trascrizione" | "diarizzazione";

/**  Lo stato di un modello per l'interfaccia. */
export type ModelState = { state: "notDownloaded" } | 
/**  Un download interrotto: il `.partial` resta e il prossimo download riprende da lì. */
{ state: "interrupted"; percent: number } | { state: "downloading"; percent: number } | 
/**  Controllo di dimensione e SHA-256 prima che il modello diventi utilizzabile. */
{ state: "verifying" } | { state: "downloaded" };

/**  Un modello ha cambiato stato: download avviato, in verifica, finito, fallito, eliminato. */
export type ModelStateChanged = {
	modelId: string,
	state: ModelState,
	error: AppError | null,
};

/**  Un Bino aperto come Sorgente: le Frasi, i nomi dei Parlanti e le informazioni. */
export type OpenedBino = {
	phrases: TranscriptPhrase[],
	/**  Per chiave `<ingresso>:<n>`, come nel Bino. */
	parlanti: { [key in string]: string },
	info: BinoInfo,
};

/**  La Registrazione salvata, che diventa la Sorgente. */
export type RecordingSaved = {
	/**  Il Bino; se non si è potuto scrivere, l'Ogg nella cartella nascosta. */
	path: string,
	/**
	 *  Perché la Registrazione si è fermata da sola (`deviceDisconnected`, `unwritableFolder`) o
	 *  perché il Bino non si è scritto; `null` dopo Stop.
	 */
	error: AppError | null,
	/**  L'esito della Trascrizione dal vivo; `null` se era spenta. */
	transcription: LiveTranscription | null,
};

export type RecordingSource = "mic" | "system" | "both";

/**  Durata registrata (pause escluse) e livelli dall'evento precedente. */
export type RecordingTick = {
	elapsedMs: number,
	levels: Levels,
};

/**  Una Frase trovata, con l'estratto in cui le parole trovate stanno tra `MARK_START` e `MARK_END`. */
export type SearchHit = {
	phraseId: number,
	ingresso: Ingresso,
	inizioMs: number,
	estratto: string,
};

/**
 *  Un Bino trovato dalla ricerca, con le Frasi trovate in ordine di inizio (nessuna se ha trovato
 *  solo il titolo).
 */
export type SearchResult = {
	bino: BinoEntry,
	frasi: SearchHit[],
};

export type Settings = {
	recordingSource: RecordingSource,
	/**  `null`: il microfono predefinito di sistema. */
	microphone: string | null,
	/**  `null`: il dispositivo di uscita predefinito, per l'audio di sistema. */
	outputDevice: string | null,
	/**  L'id del modello nel catalogo. */
	model: string,
	speechLanguage: SpeechLanguage,
	bitrateKbps: number,
	channels: Channels,
	/**  Hz. */
	sampleRate: number,
	/**  La Cartella della Libreria; `null`: `Documenti\Sbobino`. */
	recordingsFolder: string | null,
	/**  `null`: la lingua di sistema se è tra le sei, altrimenti l'inglese. */
	interfaceLanguage: Language | null,
	/**
	 *  Trascrivi dal vivo: la Registrazione trascrive mentre registra. Manca nei file salvati
	 *  prima che esistesse: allora è spenta.
	 */
	trascrizioneDalVivo?: boolean,
	/**
	 *  Cosa trascrive dal vivo una Registrazione da Entrambi. Manca nei file salvati prima che
	 *  esistesse: allora è il mix.
	 */
	modalitaDalVivo?: ModalitaDalVivo,
	/**  Il formato di Copia testo. Manca nei file salvati prima che esistesse: allora è testo. */
	copiaCome?: CopiaCome,
	/**
	 *  Riconosci i parlanti: Trascrivi su un file diarizza dopo la Trascrizione. Manca nei file
	 *  salvati prima che esistesse: allora è spenta.
	 */
	parlantiFile?: boolean,
	/**
	 *  Riconosci i parlanti di una Registrazione, dopo Stop, sul mix (Trascrizione dal vivo del
	 *  mix) o con gli Ingressi separati sul microfono e sull'audio di sistema. Mancano nei file
	 *  salvati prima che esistessero: allora sono spente.
	 */
	parlantiMix?: boolean,
	/**  Riconosci i parlanti sul microfono, con gli Ingressi separati. */
	parlantiMicrofono?: boolean,
	/**  Riconosci i parlanti sull'audio di sistema, con gli Ingressi separati. */
	parlantiSistema?: boolean,
	/**
	 *  La Raccolta scelta nella barra laterale: `null` Tutta la Libreria, `""` Senza raccolta,
	 *  altrimenti il nome. Manca nei file salvati prima che esistesse: allora è Tutta la Libreria.
	 */
	raccolta?: string | null,
};

export type SpeakerAssignment = {
	ingresso: Ingresso,
	phraseId: number,
	parlante: number | null,
};

/**
 *  I Parlanti delle Frasi dopo la Diarizzazione: `parlante` da 1 per ordine di comparsa, `null` se
 *  nessuno parlava durante la Frase.
 */
export type SpeakersAssigned = {
	speakers: SpeakerAssignment[],
};

/**  La Lingua del parlato: Automatica o una delle sei lingue dell'app. */
export type SpeechLanguage = "auto" | "it" | "en" | "fr" | "es" | "de" | "pl";

/**
 *  Il Parziale della Frase in corso (solo con i modelli in streaming): sostituisce il precedente e
 *  ha l'id che avrà la Frase. `fine_ms` è la fine dell'audio letto finora.
 */
export type TranscriptPartial = {
	phraseId: number,
	inizioMs: number,
	fineMs: number,
	text: string,
	ingresso: Ingresso,
};

/**
 *  Una Frase conclusa, una per riga nell'area di testo. Sostituisce il Parziale con lo stesso id.
 *  `inizio_ms` e `fine_ms` sono sulla linea del tempo della Sorgente.
 */
export type TranscriptPhrase = {
	phraseId: number,
	inizioMs: number,
	fineMs: number,
	text: string,
	/**  Con gli Ingressi separati ogni Ingresso ha le sue Frasi, con id propri. */
	ingresso: Ingresso,
	/**
	 *  Il Parlante, da 1: c'è nelle Frasi di un Bino diarizzato. Durante una Trascrizione arriva
	 *  dopo, con `speakers-assigned`.
	 */
	parlante: number | null,
};

/**  Esito di una Trascrizione arrivata alla fine della Sorgente. Annulla e i guasti sono `AppError`. */
export type TranscriptionOutcome = 
/**
 *  Il testo è nel Bino `path`: quello nuovo di un file, o il Bino trascritto. Diventa la
 *  Sorgente.
 */
{ outcome: "saved"; path: string } | 
/**  Nessuna Frase: un file non diventa un Bino; un Bino resta senza Frasi. */
{ outcome: "noSpeech" };

/**
 *  Avanzamento della Trascrizione, o dello smaltimento della coda dal vivo dopo Stop: `percent` è
 *  `null` se la durata della Sorgente non è nota.
 */
export type TranscriptionProgress = {
	percent: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

